/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.academy.a3mainproj;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ianns
 */
public class TelaHabitos extends javax.swing.JFrame {

    /**
     * Creates new form TelaHabitos
     */
    public TelaHabitos() {
        super("Habitos");
        initComponents();
        buscarHabitos();
        setLocationRelativeTo(null);
    }
    
    private void buscarHabitos(){
        try{
            DAO dao = new DAO();
            Habitos[] habito = dao.obterHabitos();
            cbbIdHabito.setModel(new DefaultComboBoxModel<>(habito));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Hábitos indisponíveis. Tente novamente mais tarde!");
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtNomeHabito = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        cbbGrau = new javax.swing.JComboBox<>();
        cbbIdHabito = new javax.swing.JComboBox<>();
        btnAdicionarHabito = new javax.swing.JButton();
        btnAtualizarHabito = new javax.swing.JButton();
        btnRemoverHabito = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        chkHabilitado = new javax.swing.JCheckBox();
        txtIdHabito = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Habitos");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 74, 173));

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("LiveRoutine");

        jPanel3.setBackground(new java.awt.Color(0, 39, 91));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(144, 144, 144))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txtNomeHabito.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nome do hábito", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N

        txtDescricao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descrição do hábito", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N

        cbbGrau.setBackground(new java.awt.Color(255, 255, 255));
        cbbGrau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        cbbGrau.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Grau de prática", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N

        cbbIdHabito.setBackground(new java.awt.Color(255, 255, 255));
        cbbIdHabito.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hábito", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N
        cbbIdHabito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbIdHabitoActionPerformed(evt);
            }
        });

        btnAdicionarHabito.setBackground(new java.awt.Color(255, 255, 255));
        btnAdicionarHabito.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnAdicionarHabito.setText("Adicionar hábito");
        btnAdicionarHabito.setBorder(null);
        btnAdicionarHabito.setBorderPainted(false);
        btnAdicionarHabito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarHabitoActionPerformed(evt);
            }
        });

        btnAtualizarHabito.setBackground(new java.awt.Color(255, 255, 255));
        btnAtualizarHabito.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnAtualizarHabito.setText("Atualizar Hábito");
        btnAtualizarHabito.setBorder(null);
        btnAtualizarHabito.setBorderPainted(false);
        btnAtualizarHabito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarHabitoActionPerformed(evt);
            }
        });

        btnRemoverHabito.setBackground(new java.awt.Color(255, 255, 255));
        btnRemoverHabito.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnRemoverHabito.setText("Remover Hábito");
        btnRemoverHabito.setBorder(null);
        btnRemoverHabito.setBorderPainted(false);
        btnRemoverHabito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverHabitoActionPerformed(evt);
            }
        });

        btnMenu.setBackground(new java.awt.Color(255, 255, 255));
        btnMenu.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnMenu.setText("Voltar ao Dashboard");
        btnMenu.setBorder(null);
        btnMenu.setBorderPainted(false);
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        chkHabilitado.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        chkHabilitado.setText("Habilitado");
        chkHabilitado.setContentAreaFilled(false);

        txtIdHabito.setEditable(false);
        txtIdHabito.setBackground(new java.awt.Color(255, 255, 255));
        txtIdHabito.setToolTipText("");
        txtIdHabito.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbbGrau, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkHabilitado, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNomeHabito, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbIdHabito, 0, 220, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(txtIdHabito))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnRemoverHabito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdicionarHabito, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAtualizarHabito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbbIdHabito, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdHabito, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeHabito, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkHabilitado, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbGrau, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarHabito, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizarHabito, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRemoverHabito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        TelaDashboardUsuario tbu = new TelaDashboardUsuario();
        tbu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void cbbIdHabitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbIdHabitoActionPerformed
        // TODO add your handling code here:
        Habitos habito = (Habitos) cbbIdHabito.getSelectedItem();
        txtNomeHabito.setText(habito.getNome());
        txtDescricao.setText(habito.getDescricao());
        txtIdHabito.setText(Integer.toString(habito.getId()));
        cbbGrau.setSelectedItem(habito.getGrau());
        if(habito.getHabilitado() == true){
            chkHabilitado.setSelected(true);
        }
        
        else if (habito.getHabilitado() == false){
            chkHabilitado.setSelected(false);
        }
    }//GEN-LAST:event_cbbIdHabitoActionPerformed

    private void btnAdicionarHabitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarHabitoActionPerformed
        // TODO add your handling code here:
        String nome = txtNomeHabito.getText();
        String descricao = txtDescricao.getText();
        int grau = cbbGrau.getSelectedIndex();
        boolean habilitado = chkHabilitado.isSelected();
        
        try {
            Habitos habito = new Habitos(nome, descricao, grau, habilitado);
            DAO dao = new DAO();
            dao.inserirHabito(habito);
            JOptionPane.showMessageDialog(null, "Habito inserido com sucesso!");
            buscarHabitos();
            txtNomeHabito.setText("");
            txtDescricao.setText("");
            cbbGrau.setSelectedIndex(0);
            chkHabilitado.setSelected(false);
            txtIdHabito.setText("");
        }
        
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Falha técnica, tente mais tarde");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAdicionarHabitoActionPerformed

    private void btnAtualizarHabitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarHabitoActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtIdHabito.getText());
        String nome = txtNomeHabito.getText();
        String descricao = txtDescricao.getText();
        int grau = cbbGrau.getSelectedIndex();
        boolean habilitado = chkHabilitado.isSelected();
        
        try {
            Habitos habito = new Habitos(id, nome, descricao, grau, habilitado);
            DAO dao = new DAO();
            dao.atualizarHabito(habito);
            JOptionPane.showMessageDialog(null, "Habito inserido com sucesso!");
            buscarHabitos();
            txtNomeHabito.setText("");
            txtDescricao.setText("");
            cbbGrau.setSelectedIndex(0);
            chkHabilitado.setSelected(false);
            txtIdHabito.setText("");
        }
        
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Falha técnica, tente mais tarde");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAtualizarHabitoActionPerformed

    private void btnRemoverHabitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverHabitoActionPerformed
        // TODO add your handling code here:
        int escolha = JOptionPane.showConfirmDialog(null, "Deseja deletar este hábito?");
        if(escolha == JOptionPane.YES_OPTION){
            try{
                int id = Integer.parseInt(txtIdHabito.getText());
                Habitos habito = new Habitos(id);
                DAO dao = new DAO();
                dao.removerHabito(habito);
                JOptionPane.showMessageDialog(null, "Hábito removido com sucesso!");
                buscarHabitos();
                txtNomeHabito.setText("");
                txtDescricao.setText("");
                cbbGrau.setSelectedIndex(0);
                chkHabilitado.setSelected(false);
                txtIdHabito.setText("");
            }
            catch (Exception e){
                JOptionPane.showMessageDialog(null, "Falha técnica. Tente novamente mais tarde.");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnRemoverHabitoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHabitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHabitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHabitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHabitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHabitos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarHabito;
    private javax.swing.JButton btnAtualizarHabito;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRemoverHabito;
    private javax.swing.JComboBox<String> cbbGrau;
    private javax.swing.JComboBox<Habitos> cbbIdHabito;
    private javax.swing.JCheckBox chkHabilitado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtIdHabito;
    private javax.swing.JTextField txtNomeHabito;
    // End of variables declaration//GEN-END:variables
}
